### ISSUE TITLE
Use a delta to check is a swipe has occurred

### ISSUE THREAD

**Issue by fbedussi** [marshallformula/elm-swiper#3]
Hi, thanks for the package, it's very handy. 

I have just a problem. To decide if a swipe has occurred it simply checks if the end coordinates are lesser or greater than the initial ones, this leads to an excess of sensitivity. 

For instance, I'm using it to close a side panel on swipe, but now swipe gets triggered accidentally even when user scrolls. 

It would be better to check that start and end coordinates difference is above a certain threshold, even better if that threshold is configurable.

I can submit a PR if you agree. 

Let me know 

Cheers

**Comment by marshallformula** [comment]
Hi Francesco

That sounds great to me.  I haven’t actually used this one on a project in some time.  So PR would be welcome!

Nate Gibbons

**Comment by fbedussi** [comment]
What do you think of this?
https://github.com/marshallformula/elm-swiper/pull/4

**Comment by marshallformula** [comment]
Thanks!  Sorry for the delay in merging
